sonar.projectKey=jaykay12_CricAI
sonar.organization=jaykay12

# Explicitly set the python version to clean up the analysis warning
sonar.python.version=3.11

sonar.sources=src

sonar.tests=tests
sonar.coverage.exclusions=tests/**/*,**/test_*.py

sonar.python.coverage.reportPaths=coverage.xml